FROM node:20.14-alpine as builder

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

# EXPOSE 8080
# CMD [ "npm","run","dev" ]

FROM node:20.14-alpine

WORKDIR /app

ENV NODE_ENV production
ENV HOSTNAME "0.0.0.0"

RUN npm install -g npm@10.8.1

COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/prisma .
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/package.json .

EXPOSE 8080

CMD [ "npm","run","start" ]